### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by kevinmonisit** [oss/Shrunk-Outlook-Add-In#1]
- [x] Add instructions on how to create a tracking pixel. 
 from Aaron: "We'll probably want to put a bit of an instruction write-up together into the text area, stuff like that."

- [ ] Obtain Rutgers icon logos (consult to Brian)

- [x] Multiple inserts (of invisible pixels) would lead to redundant tracking counts. Need a way to mitigate that.

- [ ] Figure out publishing

- [ ] Adding Prettier

- [x] Thinking about user experience.... (remove button, user click multiple times, shrunk link detection to remind user which link they used, etc.)

- [x] Added automatic updates between tracking pixel list and updates to the body by checking for differences in previous state (undos work, re-ordering works, redos work, etc.). This is to let the user know if they accidentally deleted the tracking pixel.

- [x] Added ability to click on box to temporarily highlight the invisible tracking pixel.

- [x] Alias extraction for go.rutgers.edu and shrunk links

- [x] Added Feedback form link
   - [x] Added fancy underline hover over animation 

- ~Make it look pretty~
